version: '3.8'

services:
  backend:
    build: ./glimere-backend
    container_name: sheerpeace-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=5432
    depends_on:
      - postgresdb

  frontend:
    build: ./glimere-frontend
    container_name: sheerpeace-frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.sheerpeace.store
    depends_on:
      - backend

volumes:
  db:
